# Generated by Django 6.0.1 on 2026-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name of the server', max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='IP Address (like 192.168.1.1)')),
                ('owner', models.CharField(help_text='Person responsible for this server', max_length=100)),
                ('ports_to_check', models.CharField(blank=True, help_text='Ports (like 80,443,22)', max_length=200, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
